#!/bin/sh

echo "Git pre-commit checks:"

formatReturn=0
checkReturn=0

echo ""
echo ""
echo "Clang-Format....................................................:"
python format.py
formatReturn="$?"

echo ""
echo ""
echo "Cppcheck........................................................:"
python check.py -GD
checkReturn="$?"

echo "Git Hook Results:"

if [[ "$formatReturn" -eq 0 ]];
then
    echo "GitHook: Clang-format....................................SUCCESS"
else
    echo "GitHook: Clang-format....................................FAILED"
fi

if [[ "$checkReturn" -eq 0 ]];
then
    echo "GitHook: CppCheck........................................SUCCESS"
else
    echo "GitHook: CppCheck........................................FAILED"
fi


if [[ "$formatReturn" -eq 0 && "$checkReturn" -eq 0 ]];
then
    exit 0
else
    exit 1
fi