#!/bin/sh

echo "Git pre-commit checks:"

formatReturn=1
checkReturn=1

python format.py

if [ $? -eq 0 ]; 
then
    echo ""
    echo "GitHook: Clang-format...................................SUCCESS"
    formatReturn=0
else
    echo ""
    echo "GitHook: Clang-format...................................FAILED"
fi

python check.py -GD

if [ $? -eq 0 ]; 
then
    echo ""
    echo "GitHook: CppCheck........................................SUCCESS"
    checkReturn=0
else
    echo ""
    echo "GitHook: ChhCheck........................................FAILED"
fi

if (( $formatReturn==0 & $checkReturn==0 ))
then
    exit 0
else
    exit 1
fi